USE profile_db;

INSERT INTO codeproject (title, body, describing_title, site_link, git_link, image_path, alt_image_text, is_group_project, valid_from_date) VALUES 
    ("Trail Finder", "As a team we collaborated on ideas for an app. We then researched available web service APIs to support the app idea. We used an agile methodology and Github Projects Board to organize ourselves. We opted for slack to serve as our daily stand up meetings. We completed this project within the week time frame we were given.", "Take A Journey", "https://jyothybaby.github.io/Trail-Finder/", "https://github.com/jyothybaby/Trail-Finder", "/images/nature.jpg", "Still Image of Trail-Finder", true, '2021/08/30')
, ("README Generator", "Demonstrates understanding of how NodeJS extends javascript to make connections between interesting libraries. This code repository may not have the wow effects that can be demonstrated in a browser being a console based tool. Yet this tool has helped me to consistently produce good README documenation for my projects.", "NodeJS Inquirer", "https://github.com/adam-niggebrugge/README_Automatic", "https://github.com/adam-niggebrugge/README_Automatic", "/images/readme_automatic.gif", "Animated image of console in action", false, '2021/08/24')
, ("Weather Forecast", "This app demonstrates use of a Server Side API Call. Uses HTML, CSS, JS, MomentJS and Boostrap. I was required to create an app that could provide weather results for any area searched by a user.", "Server Side API", "https://adam-niggebrugge.github.io/Weather_City_App/", "https://github.com/adam-niggebrugge/Weather_City_App", "/images/CitySearched.jpg", "City Weather Dashboard", false, '2021/08/16')
, ("Javascript Quiz", "A simple use of javascript for a user to enjoy a \"quiz/game\". Involves using local storage within Javascript, HTML, CSS with a little help from Bootstrap to implement a modal that records the user's name.", "User Side Javascript", "https://adam-niggebrugge.github.io/Code_Quiz_WEB_APIs/", "https://github.com/adam-niggebrugge/Code_Quiz_WEB_APIs", "/images/CodeQuizRefined.gif", "Animated view of user clicking events on a web page", false, '2021/08/16')
, ("Password Generator", "This exercise was a demonstration of handling user inputs to return a \"password\" passwordthat meets those requests. This relied on basic Javascript without being connected to any HTML. When writing this code it was to understand uses of arrays and functions.", "Array Mutation Manipulation", "https://adam-niggebrugge.github.io/03-Javascript-Password-Generator/", "https://github.com/adam-niggebrugge/03-Javascript-Password-Generator", "/images/password_generation.gif", "Animated images of passwords generated", false, '2021/09/08')
, ("Simple Blogging", "MVC architecture is some of the quickest ", "MVC Architecture", "https://nai-blog-cms.herokuapp.com/","https://github.com/adam-niggebrugge/MVC_TechBlog", "/images/MVC_demo.gif", "Animated image of MVC website", false, '2021/10/13')
, ("Easier to Read HTML", "This exercise was refactoring an existing web page so that it would meet semantic HTML. Doing this makes the webpage have a higher SEO rating in web search tools. Better SEO ratings means being ranked higher in the returned results. Also semantic HTML is easier to read. This applies to both humans and machines. Thus web pages using good semantic HTML will be easier for screen readers to read.", "Semantic HTML", "https://adam-niggebrugge.github.io/01-Horiseon_Refactored/", "https://github.com/adam-niggebrugge/01-Horiseon_Refactored/blob/", "/images/HTML_Semantic.jpg", "Image of HTML", false, '2021/07/01')
;